-- TABLE DATA_VALIDATION_CONTROL_BKP_2 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."DATA_VALIDATION_CONTROL_BKP_2" 
   (	"TEST_CASE_ID" VARCHAR2(50 CHAR), 
	"MODULE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"TEST_CASE_NAME" VARCHAR2(4000 CHAR), 
	"SCHEMA_A_QUERY" CLOB, 
	"SCHEMA_B_QUERY" CLOB, 
	"COUNT_A" NUMBER, 
	"COUNT_B" NUMBER, 
	"ERROR_A" CLOB, 
	"ERROR_B" CLOB, 
	"STATUS" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"JOB_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6)
   ) ;
