-- TABLE GLTM_INSTR_DET_UPLD_TEMP_V14 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."GLTM_INSTR_DET_UPLD_TEMP_V14" 
   (	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"INSTRUMENT_NO" VARCHAR2(16 CHAR), 
	"DESCRIPTION" VARCHAR2(105 CHAR), 
	"GL_CODE" VARCHAR2(9 CHAR), 
	"STATUS" VARCHAR2(1 CHAR), 
	"REMARKS" VARCHAR2(105 CHAR), 
	"FILE_NAME" VARCHAR2(15 CHAR), 
	"CNT1" NUMBER
   ) ;
