-- TABLE MIG_EXCEPTION_MIS_MATCH (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MIG_EXCEPTION_MIS_MATCH" 
   (	"SEQ" NUMBER, 
	"MODULE" VARCHAR2(20), 
	"QUERY_12" VARCHAR2(4000), 
	"COUNT_12" NUMBER, 
	"QUERY_14" VARCHAR2(4000), 
	"COUNT_14" NUMBER
   ) ;
