-- TABLE MIG_TABLE_ROW_COUNT_LOG (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MIG_TABLE_ROW_COUNT_LOG" 
   (	"LOG_ID" NUMBER, 
	"RUN_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ROW_ID_PROCESSED" NUMBER, 
	"TABLE_NAME_V12" VARCHAR2(128 CHAR), 
	"TABLE_NAME_V14" VARCHAR2(128 CHAR), 
	"TOTAL_COUNT_V12" NUMBER, 
	"TOTAL_COUNT_V14" NUMBER, 
	"QUALIFIED_COUNT_V12" NUMBER, 
	"STATUS" VARCHAR2(50 CHAR), 
	"ERROR_MESSAGE" VARCHAR2(4000 CHAR)
   ) ;
