-- TABLE MINUS_ICTB_CHG_VAL (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_ICTB_CHG_VAL" 
   (	"BRN" VARCHAR2(3 CHAR), 
	"ACC" VARCHAR2(20 CHAR), 
	"ELEM" VARCHAR2(20 CHAR), 
	"ITM_DT" DATE, 
	"ELEM_VAL" NUMBER, 
	"ELEM_CCY" VARCHAR2(3 CHAR), 
	"ELEM_TYPE" VARCHAR2(20 CHAR), 
	"PROD" VARCHAR2(4 CHAR)
   ) ;
