-- TABLE MINUS_CLTB_DAILY_ACC_OUT_BAL_CUSTOM (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_DAILY_ACC_OUT_BAL_CUSTOM" 
   (	"MODULE_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"ACCOUNT_CCY" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"RUN_DATE" DATE NOT NULL ENABLE, 
	"OUT_BAL_AMOUNT" NUMBER(22,3), 
	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR) NOT NULL ENABLE, 
	"BRANCH_CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE
   ) ;
