-- TABLE MINUS_STTB_NOTIFICATION_HIST_ARCH (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_STTB_NOTIFICATION_HIST_ARCH" 
   (	"BASE_TABLE" VARCHAR2(30 CHAR), 
	"PKEY_FIELDS" VARCHAR2(255 CHAR), 
	"PKEY_VALUES" VARCHAR2(255 CHAR), 
	"OPERATION" VARCHAR2(30 CHAR), 
	"PROCESS_STATUS" VARCHAR2(1 CHAR), 
	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"SEQ_NO" NUMBER, 
	"SKIP_SEQ_NO" NUMBER, 
	"REC_ROWID" VARCHAR2(100 CHAR), 
	"NOTIF_CODE" VARCHAR2(100 CHAR)
   ) ;
