-- TABLE MINUS_CLTB_AMOUNT_RECD_HISTORY (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_AMOUNT_RECD_HISTORY" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"COMPONENT_NAME" VARCHAR2(35 CHAR), 
	"RECD_DATE" DATE, 
	"BOOK_DATE" DATE, 
	"EVENT_SEQ_NO" NUMBER, 
	"RECD_TYPE" VARCHAR2(1 CHAR), 
	"AMOUNT_RECD" NUMBER, 
	"VERSION_NO" NUMBER
   ) ;
