-- TABLE MINUS_ICTB_ACC_ACTION (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_ICTB_ACC_ACTION" 
   (	"BRN" VARCHAR2(3 CHAR), 
	"TBL_NAME" VARCHAR2(30 CHAR), 
	"KEY_VAL" VARCHAR2(64 CHAR), 
	"ACTION" CHAR(1 CHAR), 
	"OLD_VAL" VARCHAR2(100 CHAR), 
	"NEW_VAL" VARCHAR2(100 CHAR), 
	"STATUS" CHAR(1 CHAR), 
	"ACC" VARCHAR2(20 CHAR), 
	"PROD" VARCHAR2(4 CHAR), 
	"AUTH_STAT" CHAR(1 CHAR), 
	"BRN_DATE" DATE, 
	"NODE" VARCHAR2(105 CHAR)
   ) ;
