-- TABLE MINUS_CLTB_ACCOUNT_COMP_BALANCES (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_ACCOUNT_COMP_BALANCES" 
   (	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"COMPONENT_NAME" VARCHAR2(20 CHAR), 
	"VAL_DATE" DATE, 
	"BALANCE" NUMBER
   ) ;
