-- TABLE MINUS_CLTB_LIQ_COMP_SETTLED (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_LIQ_COMP_SETTLED" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"EVENT_SEQ_NO" NUMBER, 
	"COMPONENT_NAME" VARCHAR2(20 CHAR), 
	"LOAN_CCY_EQUIV" NUMBER, 
	"SETTLEMENT_REF_NO" VARCHAR2(35 CHAR), 
	"COMP_CCY_EQUIV" NUMBER
   ) ;
