-- TABLE MINUS_STTM_CUST_ACCOUNT_BREAKUP (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_STTM_CUST_ACCOUNT_BREAKUP" 
   (	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"CUSTOMER_NO" VARCHAR2(9 CHAR), 
	"CUSTOMER_RUNNING_NO" VARCHAR2(9 CHAR), 
	"ACCOUNT_CODE" VARCHAR2(6 CHAR), 
	"CURRENCY_TYPE" VARCHAR2(3 CHAR), 
	"SEQUENCE_NO" NUMBER, 
	"USED_FLAG" VARCHAR2(1 CHAR)
   ) ;
