-- TABLE MINUS_ICTW_ACC_PR (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_ICTW_ACC_PR" 
   (	"BRN" VARCHAR2(3 CHAR), 
	"ACC" VARCHAR2(20 CHAR), 
	"PROD" VARCHAR2(4 CHAR), 
	"ACLASS" VARCHAR2(6 CHAR), 
	"CCY" VARCHAR2(3 CHAR), 
	"CUST" VARCHAR2(20 CHAR), 
	"CUST_CAT" VARCHAR2(10 CHAR), 
	"PROCESS" NUMBER
   ) ;
