-- TABLE MINUS_CYTB_DERIVED_RATES_HISTORY (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CYTB_DERIVED_RATES_HISTORY" 
   (	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"CCY1" VARCHAR2(3 CHAR), 
	"CCY2" VARCHAR2(3 CHAR), 
	"RATE_TYPE" VARCHAR2(8 CHAR), 
	"RATE_DT_STAMP" DATE, 
	"MID_RATE" NUMBER(24,12), 
	"BUY_RATE" NUMBER(24,12), 
	"SALE_RATE" NUMBER(24,12), 
	"MULT_FACTOR" NUMBER(14,7), 
	"POWER_FACTOR" NUMBER(10,5), 
	"RATE_FLAG" CHAR(1 CHAR), 
	"RATE_DATE" DATE, 
	"RATE_SERIAL" NUMBER(4,0)
   ) ;
