-- TABLE MINUS_CLTB_LIQ_COMP_SUMMARY (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_LIQ_COMP_SUMMARY" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"EVENT_SEQ_NO" NUMBER, 
	"COMPONENT_NAME" VARCHAR2(20 CHAR), 
	"COMPONENT_CCY" VARCHAR2(3 CHAR), 
	"AMOUNT_DUE" NUMBER, 
	"ADJ_AMOUNT" NUMBER, 
	"AMOUNT_OVERDUE" NUMBER, 
	"AMOUNT_NOT_DUE" NUMBER, 
	"AMOUNT_WAIVED" NUMBER, 
	"AMOUNT_CAPITALIZED" NUMBER, 
	"AMOUNT_PAID" NUMBER
   ) ;
