-- TABLE MINUS_CYTB_RATES_HISTORY (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CYTB_RATES_HISTORY" 
   (	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"CCY1" VARCHAR2(3 CHAR), 
	"CCY2" VARCHAR2(3 CHAR), 
	"RATE_TYPE" VARCHAR2(8 CHAR), 
	"RATE_DT_STAMP" DATE, 
	"MID_RATE" NUMBER(24,12), 
	"BUY_RATE" NUMBER(24,12), 
	"SALE_RATE" NUMBER(24,12), 
	"RATE_SERIAL" NUMBER(4,0), 
	"RATE_DATE" DATE
   ) ;
