-- TABLE MINUS_CLTB_AMOUNT_PAID (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_AMOUNT_PAID" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"COMPONENT_NAME" VARCHAR2(35 CHAR), 
	"DUE_DATE" DATE, 
	"PAID_DATE" DATE, 
	"EVENT_SEQ_NO" NUMBER, 
	"AMOUNT_PAID" NUMBER, 
	"AMOUNT_WAIVED" NUMBER, 
	"AMOUNT_CAPITALIZED" NUMBER, 
	"EXEC_DATE" DATE, 
	"PAID_STATUS" VARCHAR2(1 CHAR), 
	"START_DATE" DATE
   ) ;
