-- TABLE MINUS_CLTB_ACC_UDE_VALUES_HISTORY (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_CLTB_ACC_UDE_VALUES_HISTORY" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"EFFECTIVE_DATE" DATE, 
	"UDE_ID" VARCHAR2(30 CHAR), 
	"VERSION_NO" NUMBER(4,0), 
	"UDE_VALUE" NUMBER, 
	"RATE_CODE" VARCHAR2(20 CHAR), 
	"CODE_USAGE" VARCHAR2(1 CHAR), 
	"MAINT_RSLV_FLAG" VARCHAR2(1 CHAR), 
	"RESOLVED_VALUE" NUMBER
   ) ;
