-- TABLE MINUS_UDTB_CLEVENT_DETAIL (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_UDTB_CLEVENT_DETAIL" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"BRANCH_CODE" VARCHAR2(35 CHAR), 
	"EVENT_SEQ_NO" NUMBER, 
	"AMOUNT_TAG" VARCHAR2(35 CHAR), 
	"AMOUNT_PAID" NUMBER, 
	"CCY" VARCHAR2(3 CHAR), 
	"SETTL_ACCOUNT" VARCHAR2(35 CHAR), 
	"SETTL_BRN" VARCHAR2(3 CHAR)
   ) ;
