-- TABLE MINUS_ICTB_MAINT_QUEUE (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_ICTB_MAINT_QUEUE" 
   (	"BRN" VARCHAR2(3 CHAR), 
	"MAINT_TYPE" VARCHAR2(2 CHAR), 
	"MAINT_KEY" VARCHAR2(100 CHAR), 
	"TIMESTAMP" DATE, 
	"STATUS" VARCHAR2(1 CHAR)
   ) ;
