-- TABLE MINUS_ICTB_UDEVAL_ROW (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."MINUS_ICTB_UDEVAL_ROW" 
   (	"COND_KEY" VARCHAR2(23 CHAR), 
	"COND_TYPE" VARCHAR2(1 CHAR), 
	"PROD" VARCHAR2(4 CHAR), 
	"UDE_EFF_DT" DATE, 
	"UDE_VAL_LIST" VARCHAR2(4000 CHAR)
   ) ;
