-- TABLE POST_MIG_MIS_MATCH_COLS_ROUND1 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."POST_MIG_MIS_MATCH_COLS_ROUND1" 
   (	"TABLE_NAME" VARCHAR2(128 CHAR), 
	"COLUMN_NAME" VARCHAR2(128 CHAR), 
	"COMMON_COLUMN_VAL" VARCHAR2(128 CHAR), 
	"VALUE_A" VARCHAR2(4000 CHAR), 
	"VALUE_B" VARCHAR2(4000 CHAR)
   ) ;
