-- TABLE POST_MIG_COLUMN_ERRORS (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."POST_MIG_COLUMN_ERRORS" 
   (	"TABLE_NAME" VARCHAR2(128 CHAR), 
	"COLUMN_NAME" VARCHAR2(128 CHAR), 
	"ERROR_MSG" VARCHAR2(2000 CHAR), 
	"LOG_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;
