-- TABLE POST_MIG_COLUMN_ERRORS_MOCK3 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."POST_MIG_COLUMN_ERRORS_MOCK3" 
   (	"TABLE_NAME" VARCHAR2(128 CHAR), 
	"COLUMN_NAME" VARCHAR2(128 CHAR), 
	"ERROR_MSG" VARCHAR2(2000 CHAR), 
	"LOG_TS" TIMESTAMP (6)
   ) ;
