-- TABLE POST_MIG_MIS_MATCH_TAB (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."POST_MIG_MIS_MATCH_TAB" 
   (	"TABLE_NAME" VARCHAR2(100 CHAR), 
	"COLUMN_NAME" VARCHAR2(128 CHAR), 
	"MISMATCH_COUNT" NUMBER, 
	"QUERY_STRING" VARCHAR2(4000 CHAR), 
	"REMARKS" VARCHAR2(4000 CHAR)
   ) ;
