-- TABLE POST_MIG_HASH_ROW_MISMATCHES (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."POST_MIG_HASH_ROW_MISMATCHES" 
   (	"SCHEMA_B_NAME" VARCHAR2(128 CHAR), 
	"TABLE_B" VARCHAR2(128 CHAR), 
	"ROW_DATA_B" CLOB, 
	"LOG_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;
