-- TABLE REMAPPED_LINKAGES_1 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."REMAPPED_LINKAGES_1" 
   (	"ACCOUNT_NUMBER" VARCHAR2(35 CHAR), 
	"LINKAGE_TYPE" VARCHAR2(1 CHAR), 
	"LINKED_REFERENCE_NO" VARCHAR2(43 CHAR), 
	"CUSTOMER_ID" VARCHAR2(35 CHAR), 
	"LIAB_ID" NUMBER(20,0), 
	"ID" NUMBER(20,0), 
	"LINECODE" VARCHAR2(90 CHAR)
   ) ;
