-- TABLE STTM_ACLASS_ENTRIES_CUSTOM_VTEMP_V12 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."STTM_ACLASS_ENTRIES_CUSTOM_VTEMP_V12" 
   (	"CUSTOMER_ACCOUNT" VARCHAR2(20 CHAR), 
	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"ACC_CCY" VARCHAR2(3 CHAR), 
	"ACCOUNT_CLASS" VARCHAR2(6 CHAR), 
	"TRANSACTION_AMOUNT" NUMBER(22,3), 
	"DRCR" CHAR(1 CHAR), 
	"VALUE_DATE" DATE, 
	"TRANSACTION_DATE" DATE, 
	"CNT1" NUMBER
   ) ;
