-- TABLE STTM_CUST_ACCOUNT_18_SEP (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."STTM_CUST_ACCOUNT_18_SEP" 
   (	"CUST_AC_NO" VARCHAR2(20 CHAR), 
	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"CCY" VARCHAR2(3 CHAR), 
	"LCY_CURR_BALANCE" NUMBER, 
	"ACY_CURR_BALANCE" NUMBER, 
	"ACY_BLOCKED_AMOUNT" NUMBER, 
	"RECEIVABLE_AMOUNT" NUMBER, 
	"ACY_OPENING_BAL" NUMBER, 
	"LCY_OPENING_BAL" NUMBER, 
	"ACCOUNT_TYPE" VARCHAR2(1 CHAR)
   ) ;
