-- TABLE STTM_ACCOUNT_CHG_CUSTOM_HST_TEMP_V14 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."STTM_ACCOUNT_CHG_CUSTOM_HST_TEMP_V14" 
   (	"ACCOUNT_NO" VARCHAR2(20 CHAR), 
	"PRODUCT_CODE" VARCHAR2(4 CHAR), 
	"CHG_CCY" VARCHAR2(3 CHAR), 
	"VARIANCE" NUMBER, 
	"WAIVER" VARCHAR2(1 CHAR), 
	"MIN_MAX_CHARGE" VARCHAR2(1 CHAR), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"FIXED_VARIANCE" NUMBER, 
	"DATE_OF_CHANGE" DATE, 
	"MOD_NO" NUMBER, 
	"CNT1" NUMBER
   ) ;
