-- VIEW STTM_TR_CUST_PARTY_V14 (ARUNN_ADMIN)

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARUNN_ADMIN"."STTM_TR_CUST_PARTY_V14" ("CUSTOMER_NO", "PARTY_CODE_TYPE", "PARTY_CODE", "DEFAULT_PARTY", "PARTY_NAME", "COMMENTS") AS 
  SELECT "CUSTOMER_NO","PARTY_CODE_TYPE","PARTY_CODE","DEFAULT_PARTY","PARTY_NAME","COMMENTS" FROM INTEGRATEDPP.STZM_TR_CUST_PARTY
;
