-- VIEW STVW_TR_CUST_DEF_PARTY_V14 (ARUNN_ADMIN)

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARUNN_ADMIN"."STVW_TR_CUST_DEF_PARTY_V14" ("CUSTOMER_NO", "PARTY_CODE_TYPE", "PARTY_CODE", "DEFAULT_PARTY", "PARTY_NAME", "COMMENTS") AS 
  select "CUSTOMER_NO","PARTY_CODE_TYPE","PARTY_CODE","DEFAULT_PARTY","PARTY_NAME","COMMENTS"
from arunn_admin.sttm_tr_cust_party_v14 p
where p.DEFAULT_PARTY = 'Y'
;
