-- TABLE SWTB_INTRADAY_LOG_TEMP_V14 (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."SWTB_INTRADAY_LOG_TEMP_V14" 
   (	"BRANCH_CODE" VARCHAR2(3 CHAR), 
	"STATUS" VARCHAR2(20 CHAR), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"CNT1" NUMBER
   ) ;
