-- TABLE TABLE_VOL_SAMPLE (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."TABLE_VOL_SAMPLE" 
   (	"SCHEMA_A_TABLE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"COMMON_COLUMNS" VARCHAR2(500 CHAR), 
	"TABLE_SIZE_CATEGORY" VARCHAR2(10 CHAR), 
	"REMARKS" VARCHAR2(100 CHAR), 
	"ORCL_COMM" VARCHAR2(4000 CHAR), 
	"JM3REMARKS" VARCHAR2(2000 CHAR), 
	"NUM_ROWS" NUMBER
   ) ;
