-- TABLE TABLE_COMPARISON_LOGS (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."TABLE_COMPARISON_LOGS" 
   (	"LOG_ID" NUMBER, 
	"JOB_NAME" VARCHAR2(200 CHAR), 
	"SCHEMA_A_NAME" VARCHAR2(50 CHAR), 
	"SCHEMA_B_NAME" VARCHAR2(50 CHAR), 
	"SCHEMA_A_TABLE" VARCHAR2(100 CHAR), 
	"SCHEMA_B_TABLE" VARCHAR2(100 CHAR), 
	"STATUS" VARCHAR2(50 CHAR), 
	"ERROR_MESSAGE" VARCHAR2(1000 CHAR), 
	"LOG_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;
