-- VIEW TABLE_SIZES (ARUNN_ADMIN)

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARUNN_ADMIN"."TABLE_SIZES" ("SCHEMA_A_NAME", "SCHEMA_B_NAME", "SCHEMA_A_TABLE", "SCHEMA_B_TABLE", "COMMON_COLUMNS", "RUN_STATUS", "CHECK_FLAG", "ERROR_CODE", "TABLE_SIZE_CATEGORY", "DB_LINK", "FINAL_STAT", "REMARKS", "WHERE_CONDITION", "ORCL_COMM", "JM3REMARKS", "NUM_ROWS") AS 
  select a."SCHEMA_A_NAME",a."SCHEMA_B_NAME",a."SCHEMA_A_TABLE",a."SCHEMA_B_TABLE",a."COMMON_COLUMNS",a."RUN_STATUS",a."CHECK_FLAG",a."ERROR_CODE",a."TABLE_SIZE_CATEGORY",a."DB_LINK",a."FINAL_STAT",a."REMARKS",a."WHERE_CONDITION",a."ORCL_COMM",a."JM3REMARKS",b.num_rows from table_comparison_control a, all_tables b
where a.schema_B_table=b.table_name
;
