-- TABLE TEST_NO_PK (ARUNN_ADMIN)

  CREATE TABLE "ARUNN_ADMIN"."TEST_NO_PK" 
   (	"BRN" VARCHAR2(3 CHAR), 
	"ACC" VARCHAR2(20 CHAR), 
	"AC_OPEN_DT" DATE, 
	"REDEMPTION_DT" DATE, 
	"TD_RATE_CODE" VARCHAR2(10 CHAR), 
	"REDEMPTION_AMT" NUMBER, 
	"BOOK_DT_BOOK_TNR" NUMBER, 
	"RED_DT_BOOK_TNR" NUMBER, 
	"RED_DT_ELAP_TNR" NUMBER, 
	"INT_RATE_PICKED" NUMBER, 
	"ORIG_UDEROW" VARCHAR2(4000 CHAR), 
	"NEW_UDEROW" VARCHAR2(4000 CHAR), 
	"CNT1" NUMBER
   ) ;
